Small Readme suggestions
serpapi/nokolexbor pull request #3
Opened 2022-12-19 23:10 UTC by hartator

Excellent work @zyc9012. Thank you again! 💯 

This PR is just a couple of small suggestions to improve the Readme. Mostly clarifying Install instructions, a little more aggressiveness in the marketing of the introduction, and mirroring a little more Nokogiri's own Readme quickstart.

2022-12-20 22:38 UTC, zyc9012 requested changes
Thanks @hartator 👍, just some minor changes.

It's only for HTML parsing, does not handle general XML well at the moment.

Let's also update the example selectors to fit the contents of `URI.open('https://github.com/serpapi/nokolexbor')`

```
# Search for nodes by css
doc.css('#readme h1', 'article h2', 'p[dir=auto]').each do |link|
  puts link.content
end

# Search for text nodes by css
doc.css('#readme p > ::text').each do |text|
  puts text.content
end

# Search for nodes by xpath
doc.xpath('//div[@id="readme"]//h1', '//article//h2').each do |link|
  puts link.content
end
```

2022-12-20 22:38 UTC, zyc9012 commented on README.md
> +It's a performance-focused HTML/XML parser for Ruby based on [Lexbor](https://github.com/lexbor/lexbor/). It supports both CSS selectors and XPath. Nokolexbor's API is designed to be 1:1 compatible a
```suggestion
It's a performance-focused HTML parser for Ruby based on [Lexbor](https://github.com/lexbor/lexbor/). It supports both CSS selectors and XPath. Nokolexbor's API is designed to be 1:1 compatible as much as possible with [Nokogiri's API](https://github.com/sparklemotion/nokogiri).
```

2022-12-20 23:53 UTC, hartator commented
All sounds good @zyc9012. I've just made the updates. 👍

2022-12-21 00:28 UTC, zyc9012 approved these changes
All looks good, thank you @hartator 👍

2022-12-21 00:35 UTC, merged